Moonshot cli
OLSF/libra pull request #409
Opened 2021-03-20 15:11 UTC by lpgeiger

- [ ] cli tool to monitor node and chain info https://github.com/OLSF/libra/issues/398
- [ ] web tool to monitor node https://github.com/OLSF/libra/issues/399
- [ ] db-restore tool automation `ol restore`
- [ ] a state-machine for onboarding flow, triggering next actions `ol onboard`
- [ ] simple queries for balance, height https://github.com/OLSF/libra/issues/385
- [ ] management tools, to start and stop node and miner, and clear inactive processes
- [ ] minimal block explorer https://github.com/OLSF/libra/issues/396
- [ ] patch val-wizard with ip address issues https://github.com/OLSF/libra/issues/395

2021-03-20 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OLSF/libra?pullRequest=409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/OLSF/libra?pullRequest=409) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: liangping<br/>:x: lpgeiger<br/>:x: simsekgokhan<br/><hr/>**lpgeiger** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OLSF/libra?pullRequest=409) it.</sub>

2021-03-22 02:45 UTC, zmanian commented on ol-cli/src/machine.rs
> +// pub mod node_state_machine {
I entirely understand what this commented out bit is for? is it supposed to tell me something about `sm!` macro?

2021-03-22 02:45 UTC, zmanian commented on ol-cli/src/machine.rs
> +            // reverse
Confusing comment

2021-03-22 02:45 UTC, zmanian commented on ol-cli/src/machine.rs
> +            // reverse, the node falls
also confusing.

2021-03-22 02:50 UTC, zmanian commented
Generally this app seems really cool.

It's extremely difficult to maintain or review in it's current state.

It needs a top level explainer and then several files need short one sentence comments about what the functions do.

2021-03-22 02:53 UTC, zmanian requested changes

2021-03-22 02:53 UTC, zmanian commented on miner/src/submit_tx.rs
>  pub fn get_params(
Comment would be really helpful here.

2021-03-22 14:50 UTC, lpgeiger commented
@zmanian Thanks for jumping in. Wasn't quite ready for review. @simsekgokhan Let's add some documentation as ZM suggests.

2021-03-23 21:45 UTC, lpgeiger commented on miner/src/submit_tx.rs
>  pub fn get_params(
done

2021-03-31 22:51 UTC, merged